name = "Poolen Hugo Theme"
license = "MIT"
licenselink = "https://github.com/LICENSE.md"
description = "Hugo Theme for Rollspelspoolen campaigns"
homepage = "https://github.com/tehlastjuan/gohugo-theme-poolen"
tags = ["website", "responsive"]
features = ["related content"]
min_version = "0.128.0"
